apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: {{ .Values.serviceAccount.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        nodepool: {{ .Values.nodepool }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ACR_URL
              value: {{ .Values.acrUrl | quote }}
          volumeMounts:
            - name: log
              mountPath: /log
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: app-log-pvc
